{{- if .Values.server.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "teamcity-server.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "teamcity-server.labels" . | nindent 4 }}
  {{- with .Values.server.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.server.serviceAccount.automount }}
{{- end }}