apiVersion: v1
kind: Service
metadata:
  name: teamcity-server
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "teamcity-server.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.server.service.port }}
      targetPort: http
  selector:
    app: teamcity-server
    component: server
  type: {{ .Values.server.service.type }}

---
apiVersion: v1
kind: Service
metadata:
  name: teamcity-server-headless
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "teamcity-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: false
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.server.service.port }}
      targetPort: http
  selector:
    app: teamcity-server
    component: server

---
{{- range $i := until (int .Values.server.replicas) }}
apiVersion: v1
kind: Service
metadata:
  name: teamcity-server-direct-{{ $i }}
  namespace: {{ $.Values.namespace }}
  annotations:
    node-id: "teamcity-server-{{ $i }}"
  labels:
    {{- include "teamcity-server.labels" $ | nindent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ $.Values.server.service.port }}
      targetPort: http
  selector:
    app: teamcity-server
    component: server
    statefulset.kubernetes.io/pod-name: teamcity-server-{{ $i }}
  type: ClusterIP
---
{{- end }}

{{- if .Values.proxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: teamcity-server-proxy
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "teamcity-server.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  selector:
    app: teamcity-server-proxy
    component: proxy
  type: ClusterIP
{{- end }}